theme = "kanagawa"

[editor]
line-number = "relative"
auto-save = true
color-modes = true
true-color = true
bufferline = "always"

[editor.lsp]
display-inlay-hints = true


[keys.normal]
"esc" = ["collapse_selection", ":w"]

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]

[keys.insert]
"esc" = ["normal_mode", ":w"]

# config.toml
[keys.normal."'"]
y = ":sh zellij run --floating -n 'yazi picker' --width 80% -x 10% --height 80% -y 10% -- /home/ubuntu/.config/helix/open_in_helix_from_yazi.sh"

f = ":sh zellij run --floating -n 'Terminal' --width 80% -x 10% --height 80% -y 10% -c -- bash"
