theme = "kanagawa"

[editor]
line-number = "relative"
auto-save = true
color-modes = true
true-color = true
bufferline = "always"

[editor.lsp]
display-inlay-hints = true


[keys.normal]
"esc" = ["collapse_selection", ":w"]

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]

[keys.insert]
"esc" = ["normal_mode", ":w"]

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

# config.toml
[keys.normal."'"]
y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

f = ":sh zellij run --floating -n 'Terminal' --width 80% -x 10% --height 80% -y 10% -c -- bash"

r = ":reset-diff-change"

l = [
  ':insert-output lazygit',
  ':redraw',
]


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control","spacer", "diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
